### ISSUE TITLE
generated Password only correct for 1st use?

### ISSUE THREAD

**Issue by kyrios** [datr/MobilePASSER#2]
Hi,

awesome work by you!

But I think I'm missing something. The 1st generated password is correct. But how do you increment the counter for following passwords?

I posted the question also on stackoverflow.

http://crypto.stackexchange.com/questions/20880/how-does-safenet-mobilepass-calculate-the-counter-for-following-passwords

Any hints are much appreciated.

**Comment by datr** [comment]
Hi kyrios,

Sorry for the delay in getting back to you!

You should be able to increment the counter by changing the number on this line:

https://github.com/datr/MobilePASSER/blob/python/mobilepass.py#L89

I've just tested the first few numbers and comparing with the output of the latest android application and it still seems to match. Are you seeing different results?

**Comment by datr** [comment]
I'm going to close this for now. Feel free to get in touch though if you are able to recreate the issue.
